name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca44a814425061aded7e7eb05806ad4a4b678c824c9f068b6eab8a38c2119937"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
