name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5db91f0a869cf9e528ea179e6dcec02e477cbffa12dc9208dd85270d082d943e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
