name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5240a13f526436d493e2b88f8d2e631ecd8aa8265286bc8b276bda1a95e00eb5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
