name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "985614d7fc0211fd8c7a6670dee9b67c4d886224e8c6af1e855dfd953ee2c382"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
