name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a147c533707cdd3c9ff46d53a53f8236e0cd0b5b16f5f892276776f2ba7564a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
