name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9306433acb1a2397585bd3849cb3f07acaf5fd9cafe2c45beb9164427507f07"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
