name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e2965dd68b02b76d7185b3ea0265929c3e106048ccff0fa11457f6c6d7b5a35"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
