name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00860625fbf6ec0764623c4dbdb2fa0950c5338538c620dd51994173fdd963ff"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
