name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f1e3cd03adbbb71da85a81576b2f0b4b485c02382942571cfbe291ba9c85b18"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
