name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d961954ca15a3f93128314fcdfa77237fcf833df5a3b7392b2b9a78d3c45dc5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
