name = "Infinite Revolution 1.12"
author = "Sinbelisk"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0362a4791e7f7560f9826d808421611d7ea8e65cc207af44cf644b6cad5ffff4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
